### ISSUE TITLE
Segfault when ending vk::CommandBuffer

### ISSUE THREAD

**Issue by therealnv6** [therealnv6/vx-gfx#5]
https://github.com/therealnv6/vx-gfx/blob/71c565f78be779258b9a29da2b4bf5766e8944b3/src/framework.cpp#L43

**Comment by therealnv6** [comment]
Not related to vk::CommandBuffer::end().
this prints <https://github.com/therealnv6/vx-gfx/blob/55fd6a49fd7a0c594d498efc9775bbc6acb5c10a/src/framework.cpp#L49>
this also prints <https://github.com/therealnv6/vx-gfx/blob/55fd6a49fd7a0c594d498efc9775bbc6acb5c10a/include/context.h#L279>
but this doesn't <https://github.com/therealnv6/vx-gfx/blob/55fd6a49fd7a0c594d498efc9775bbc6acb5c10a/src/framework.cpp#L52>

**Comment by dashwastakenx** [comment]
use assembely!
